User clamav
Foreground yes
LocalSocket /tmp/clamd.sock
LocalSocketMode 666
FixStaleSocket yes
DatabaseDirectory /var/lib/clamav
TemporaryDirectory /tmp
StreamMaxLength 64M
MaxFileSize 64M
MaxScanSize 128M
MaxScanTime 20000
MaxRecursion 16
MaxFiles 1000
AlertExceedsMax yes
MaxThreads 2
MaxQueue 8
ReadTimeout 30
CommandReadTimeout 10
LogTime yes
