name: Gryt trigger schema B1
on:
  push:
    branches: [fix/gryt-git-notify-events]
  pull_request_review:
    types: [submitted]
  pull_request_review_comment:
    types: [created]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo ok
