name: Gryt trigger schema B2
on:
  push:
    branches: [fix/gryt-git-notify-events]
  commit_comment:
  discussion:
    types: [created, answered, unanswered]
  discussion_comment:
    types: [created]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo ok
